"use client";

import Link from "next/link";
import { useStrategy } from "@/hooks/useStrategy";
import { StrategyCard } from "@/components/strategy/StrategyCard";
import { ArrowLeft, Loader2, AlertCircle } from "lucide-react";

export default function StrategyPage({ params }: { params: { id: string } }) {
  const { data: strategy, isLoading, error } = useStrategy(params.id);

  return (
    <main className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-3xl px-4 py-10">
        <Link
          href="/strategy/new"
          className="mb-6 flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Strategy Generator
        </Link>

        <h1 className="mb-2 text-2xl font-bold text-gray-900">Strategy {params.id.slice(0, 8)}…</h1>
        <p className="mb-8 text-sm text-gray-500">Full GTM strategy generated by ReachGTM agents</p>

        {isLoading && (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="h-6 w-6 animate-spin text-blue-600" />
          </div>
        )}

        {error && (
          <div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4">
            <AlertCircle className="h-5 w-5 text-red-600" />
            <p className="text-sm text-red-700">
              {error instanceof Error ? error.message : "Failed to load strategy"}
            </p>
          </div>
        )}

        {strategy && (
          <div className="space-y-6">
            <StrategyCard strategy={strategy} />

            {/* ICP Details */}
            {strategy.icp && (
              <div className="rounded-xl border bg-white p-6 shadow-sm">
                <h2 className="mb-4 text-lg font-semibold text-gray-900">Ideal Customer Profile</h2>
                <dl className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <dt className="text-gray-400">Title</dt>
                    <dd className="font-medium text-gray-900">{strategy.icp.title}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Industry</dt>
                    <dd className="font-medium text-gray-900">{strategy.icp.industry}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Company Size</dt>
                    <dd className="font-medium text-gray-900">{strategy.icp.company_size}</dd>
                  </div>
                  <div>
                    <dt className="text-gray-400">Budget Range</dt>
                    <dd className="font-medium text-gray-900">{strategy.icp.budget_range}</dd>
                  </div>
                </dl>

                {strategy.icp.pain_points.length > 0 && (
                  <div className="mt-4">
                    <p className="mb-2 text-xs font-medium uppercase tracking-wide text-gray-400">Pain Points</p>
                    <ul className="list-inside list-disc space-y-1 text-sm text-gray-700">
                      {strategy.icp.pain_points.map((p, i) => (
                        <li key={i}>{p}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}

            {/* Positioning */}
            <div className="rounded-xl border bg-white p-6 shadow-sm">
              <h2 className="mb-4 text-lg font-semibold text-gray-900">Positioning</h2>
              <p className="text-sm leading-relaxed text-gray-700">{strategy.positioning_statement}</p>
              <div className="mt-4 inline-block rounded-full bg-blue-50 px-3 py-1 text-sm font-medium text-blue-700">
                {strategy.motion.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}
              </div>
            </div>

            <p className="text-xs text-gray-400">
              Generated {new Date(strategy.generated_at).toLocaleString()}
            </p>
          </div>
        )}
      </div>
    </main>
  );
}
