"use client";

import Link from "next/link";
import { useStrategy } from "@/hooks/useStrategy";
import { StrategyCard } from "@/components/strategy/StrategyCard";
import { ArrowLeft, Loader2, AlertCircle } from "lucide-react";

export default function StrategyDetailClient({ id }: { id: string }) {
  const { data: strategy, isLoading, error } = useStrategy(id);

  // GET /strategy/{id} returns the stored record; only a fully generated
  // strategy carries these fields. Guard so a record without them degrades
  // gracefully instead of crashing on undefined.replace()/.slice().
  const hasContent = Boolean(strategy?.positioning_statement && strategy?.motion);

  return (
    <main className="mx-auto max-w-3xl px-5 py-12 sm:px-8 sm:py-16">
      <Link
        href="/strategy/new"
        className="mb-7 inline-flex items-center gap-1.5 text-[0.8125rem] font-medium text-ink-muted transition-colors hover:text-ink"
      >
        <ArrowLeft className="h-4 w-4" />
        Strategy generator
      </Link>

      <header className="animate-rise mb-8">
        <p className="eyebrow">Strategy</p>
        <h1 className="display mt-2 text-[2.25rem] font-medium leading-tight text-ink">
          <span className="mono align-middle text-[1.25rem] text-ink-muted">
            #{id.slice(0, 8)}
          </span>
        </h1>
        <p className="mt-2 text-[0.9375rem] text-ink-muted">
          Full go-to-market strategy generated by the ReachGTM agents.
        </p>
      </header>

      {isLoading && (
        <div className="flex items-center justify-center py-24">
          <Loader2 className="h-6 w-6 animate-spin text-flare-600" />
        </div>
      )}

      {error && (
        <div className="alert alert-danger items-center">
          <AlertCircle className="h-5 w-5 shrink-0" />
          <p>
            {error instanceof Error ? error.message : "Failed to load strategy"}
          </p>
        </div>
      )}

      {strategy && !hasContent && (
        <div className="alert items-center">
          <AlertCircle className="h-5 w-5 shrink-0" />
          <p>
            This strategy has no generated content yet. Run a generation from the
            strategy generator to populate it.
          </p>
        </div>
      )}

      {strategy && hasContent && (
        <div className="space-y-5">
          <StrategyCard strategy={strategy} />

          {/* ICP Details */}
          {strategy.icp && (
            <div className="card p-6 sm:p-7">
              <h2 className="text-[0.9375rem] font-semibold text-ink">
                Ideal customer profile
              </h2>
              <div className="rule mt-4 mb-5" />
              <dl className="grid grid-cols-2 gap-5 text-[0.875rem]">
                <div>
                  <dt className="eyebrow">Title</dt>
                  <dd className="mt-1 font-semibold text-ink">{strategy.icp.title}</dd>
                </div>
                <div>
                  <dt className="eyebrow">Industry</dt>
                  <dd className="mt-1 font-semibold text-ink">
                    {strategy.icp.industry}
                  </dd>
                </div>
                <div>
                  <dt className="eyebrow">Company size</dt>
                  <dd className="mt-1 font-semibold text-ink">
                    {strategy.icp.company_size}
                  </dd>
                </div>
                <div>
                  <dt className="eyebrow">Budget range</dt>
                  <dd className="mt-1 font-semibold text-ink">
                    {strategy.icp.budget_range}
                  </dd>
                </div>
              </dl>

              {strategy.icp.pain_points.length > 0 && (
                <div className="mt-6">
                  <p className="eyebrow mb-2.5">Pain points</p>
                  <ul className="space-y-1.5 text-[0.875rem] text-ink">
                    {strategy.icp.pain_points.map((p, i) => (
                      <li key={i} className="flex gap-2.5">
                        <span className="mono mt-0.5 text-[0.6875rem] text-flare-600">
                          0{i + 1}
                        </span>
                        <span className="leading-relaxed">{p}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {/* Positioning */}
          <div className="card p-6 sm:p-7">
            <h2 className="text-[0.9375rem] font-semibold text-ink">Positioning</h2>
            <div className="rule mt-4 mb-5" />
            <p className="display text-[1.125rem] font-normal leading-relaxed text-ink">
              {strategy.positioning_statement}
            </p>
            <div className="mt-5">
              <span className="chip chip-flare">
                {strategy.motion
                  .replace(/_/g, " ")
                  .replace(/\b\w/g, (c) => c.toUpperCase())}
              </span>
            </div>
          </div>

          <p className="mono text-[0.6875rem] text-ink-faint">
            Generated {new Date(strategy.generated_at).toLocaleString()}
          </p>
        </div>
      )}
    </main>
  );
}
